### ISSUE TITLE
Cannot read property rotateImage of undefined

### ISSUE THREAD

**Issue by udayanid** [ggunti/react-native-amazing-cropper#10]
Everything works in android but I am getting this error "Cannot read property rotateImage of undefined" in IOS when I click on DONE. Weird thing is rotate button does work correctly but the error comes when I click on DONE button.

Version:
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-image-rotate": "^2.1.0",
    "react-native-amazing-cropper": "0.0.9"

IOS Device: iPhone SE

**Comment by udayanid** [comment]
Nevermind. It worked after giving `pod install` command.

**Comment by whileMeAwakeMeCode** [comment]
I have the same issue here. 
I've done :
 - npm install --save react-native-image-rotate
 - react-native link react-native-image-rotate
 - npm install --save react-native-amazing-cropper
 - cd ios && pod install 
and I still have a typeError: null is not an object (evaluating 'RCTImageRotateModule.rotateImage').

Version:
"react": "16.9.0",
"react-native": "0.61.4",
"react-native-image-rotate": "^2.1.0",
"react-native-amazing-cropper": I tried "0.0.9" and "^0.1.1"

What did I wrong ?

**Comment by 1appstudio** [comment]
if I suppose already have a pod file, What can I do?

**Comment by Gopalakrishnan-V** [comment]
> I have the same issue here.
> I've done :
> 
> * npm install --save react-native-image-rotate
> * react-native link react-native-image-rotate
> * npm install --save react-native-amazing-cropper
> * cd ios && pod install
>   and I still have a typeError: null is not an object (evaluating 'RCTImageRotateModule.rotateImage').
> 
> Version:
> "react": "16.9.0",
> "react-native": "0.61.4",
> "react-native-image-rotate": "^2.1.0",
> "react-native-amazing-cropper": I tried "0.0.9" and "^0.1.1"
> 
> What did I do wrong ?

Did you find any solution? @whileMeAwakeMeCode

**Comment by whileMeAwakeMeCode** [comment]
@Gopalakrishnan-V 
No solution yet, unfortunately ... 
I'll come back here and share if I found anything.
