### ISSUE TITLE
onDone Handler

### ISSUE THREAD

**Issue by vinirk** [ggunti/react-native-amazing-cropper#11]
I getting this issue here when I call onDone event.

`null is not an object (evaluating 'RCTImageRotateModule.rotateImage')

rotateImage
    index.js:30:25
onDone
    Cropper.page.js:598:6
touchableHandlePress
    TouchableOpacity.js:235:45
_performSideEffectsForTransition
    Touchable.js:878:34
_receiveSignal
    Touchable.js:777:44
touchableHandleResponderRelease
    Touchable.js:488:24
invokeGuardedCallbackImpl
    ReactNativeRenderer-dev.js:93:15
invokeGuardedCallback
    ReactNativeRenderer-dev.js:318:36
invokeGuardedCallbackAndCatchFirstError
    ReactNativeRenderer-dev.js:342:30
executeDispatch
    ReactNativeRenderer-dev.js:715:42
executeDispatchesInOrder
    ReactNativeRenderer-dev.js:737:20
executeDispatchesAndRelease
    ReactNativeRenderer-dev.js:894:29
forEachAccumulated
    ReactNativeRenderer-dev.js:874:16
runEventsInBatch
    ReactNativeRenderer-dev.js:1050:21
runExtractedEventsInBatch
    ReactNativeRenderer-dev.js:1072:19
<unknown>
    ReactNativeRenderer-dev.js:2708:6
batchedUpdates$1
    ReactNativeRenderer-dev.js:18527:14
batchedUpdates
    ReactNativeRenderer-dev.js:2611:31
_receiveRootNodeIDEvent
    ReactNativeRenderer-dev.js:2706:17
receiveTouches
    ReactNativeRenderer-dev.js:2782:28
__callFunction
    MessageQueue.js:366:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:314:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17
`

**Comment by osmancikjan** [comment]
You have to run `pod install` command from ios folder of your project after you are done with 3 install steps. Possible duplicate #10

**Comment by osmancikjan** [comment]
#10

**Comment by ggunti** [comment]
@osmancikjan Yes. I included the `pod install` step in the readme.
