### ISSUE TITLE
Not working in latest version of react native

### ISSUE THREAD

**Issue by AmareshNeelgar** [ggunti/react-native-amazing-cropper#17]
react: 16.9.0
react-native: 0.61.2

We need to use @react-native-community/image-editor for editing.

![2019-11-18](https://user-images.githubusercontent.com/40197183/69044949-de686600-0a1b-11ea-894a-70e7f9bb0afa.jpg)

**Comment by ggunti** [comment]
Thanks for the issue!
@react-native-community/image-editor was added as peerdependency and readme updated.
