### ISSUE TITLE
rotateImage of undefined

### ISSUE THREAD

**Issue by Delevarius** [ggunti/react-native-amazing-cropper#20]
Everything seems to work fine untill I click the done button, and i get this error message

ExceptionsManager.js:74 Cannot read property 'rotateImage' of undefined

Which is funny, because the rotate button works just fine

**Comment by ggunti** [comment]
Maybe you forgot the `react-native link react-native-image-rotate @react-native-community/image-editor` or `pod install` (in case of rn >= 0.60) step from installation. If you made this step and still not work, please let me know which version of react-native you use and which platform (android or iOS).

**Comment by Delevarius** [comment]
I did this and it said they are already linked , but the error persists. 

I am running react native 0.59.9 currently

**Comment by ggunti** [comment]
I understand. Please show me your code and let me know on which platform you get the described error.

**Comment by Delevarius** [comment]
I am just trying to handle the example.
The rotation button works great
I just want to see the  done function

```
import React, { Component } from 'react';
import AmazingCropper, { DefaultFooter } from 'react-native-amazing-cropper';

class ImageCropper extends Component {
  onDone = (croppedImageUri) => {
    console.log('croppedImageUri = ', croppedImageUri);
    // send image to server for example
  }

  onCancel = () => {
    console.log('Cancel button was pressed');
    // navigate back
  }

  render() {
    return (
      <AmazingCropper
        // Pass custom text to the default footer
        footerComponent={<DefaultFooter doneText='OK' rotateText='ROT' cancelText='BACK' />}
        onDone={this.onDone}
        onCancel={this.onCancel}
        imageUri='https://www.lifeofpix.com/wp-content/uploads/2018/09/manhattan_-11-1600x2396.jpg'
        imageWidth={1600}
        imageHeight={2396}
      />
    );
  }
```
Just as I click the done button, I get this error
![error](https://user-images.githubusercontent.com/11784607/69872596-18582880-12b6-11ea-8d9f-adc00c4312dd.png)

**Comment by ggunti** [comment]
You said that you get `Cannot read property 'rotateImage' of undefined` error

**Comment by Delevarius** [comment]
Apologies, wrong screenshot
here is the correct one

![ErrorCrop](https://user-images.githubusercontent.com/11784607/69948863-a7508500-14f0-11ea-8406-0f9b4cc439ee.png)

**Comment by ggunti** [comment]
The problem is that `react-native-image-rotate` is not linked. I recommend you to check again STEPS TO INSTALL section inside documentation and try to do each step again. Do them step by step (order is important).
