### ISSUE TITLE
Footer Issue

### ISSUE THREAD

**Issue by 1appstudio** [ggunti/react-native-amazing-cropper#27]
Please refer this image by using this https://www.dropbox.com/s/yelq9jy8dkz9s0n/Unknown-4.PNG?dl=0

How can I fix footer..

**Comment by 1appstudio** [comment]
Check the bottom buttons its cut off.

**Comment by ggunti** [comment]
You could use the `COMPONENT_HEIGHT` prop.
Please check this [issue](https://github.com/ggunti/react-native-amazing-cropper/issues/30).
