### ISSUE TITLE
camera image rotate 90 degree

### ISSUE THREAD

**Issue by Anand8293** [ggunti/react-native-amazing-cropper#29]
when i click image from camera and crop then image automatically rotate 90 degree only in ios android working perfectly.

**Comment by ggunti** [comment]
So, when you load the image into the cropper it has correct orientation, but after the cropping happened, the image is automatically rotated 90 degree. This is the problem? If yes, please open a new issue and provide some code, or an example project. I did not face this problem yet. Also, please specify which iOS version you use.
