### ISSUE TITLE
RN is depreciating ImageStore

### ISSUE THREAD

**Issue by joshwinter** [ggunti/react-native-amazing-cropper#3]
Thanks for a great component. I just found out RN has depreciated ImageStore and left us with no good alternatives react-native-fs doesn't havegetBase64ForTag functionality. Do you know a way the image can be put right away into base64 after cropping?

**Comment by ggunti** [comment]
ImageStore still can be used in react native, but I'll try to find an alternative for this when it will be removed

**Comment by joshwinter** [comment]
Thanks much!
