### ISSUE TITLE
Is there any way to get rid of left/right image container padding?

### ISSUE THREAD

**Issue by sergiulucaci** [ggunti/react-native-amazing-cropper#31]
Despite the width set for images, there's a left and right padding for the container of the image that I can't control. In the example below I set as width the device's width (375). But the output width seems to be 275.

**Code**:
```
<AmazingCropper
  // other props..
  imageUri='https://www.lifeofpix.com/wp-content/uploads/2018/09/manhattan_-11-1600x2396.jpg'
  imageWidth={375}
  imageHeight={375}
/>
```

**Output**:
<img width="370" alt="Screenshot 2020-05-15 10 36 56" src="https://user-images.githubusercontent.com/16645155/82024317-454b9c80-9698-11ea-917c-73399b218efb.png">

**Comment by ggunti** [comment]
`imageWidth` and `imageHeight` should be the width and the height of the image, not the device width and height. So, for example, in case of [this image](https://www.lifeofpix.com/wp-content/uploads/2018/09/manhattan_-11-1600x2396.jpg), you should use `imageWidth={1600}` and `imageHeight={2396}`.

As I understand, you want to control the borders, so you could use the `BORDER_WIDTH` property (see readme file).

**Comment by sergiulucaci** [comment]
I used device's width just for example. Sorry, I overlooked BORDER_WIDTH, I was thinking it refers to the cropper-layer border-width. Thank you a lot!

**Comment by ggunti** [comment]
You're welcome. By the way, I see that you're also from Cluj-Napoca 🤪

**Comment by sergiulucaci** [comment]
Wha, this world is so small! You're doing great job with this library, congrats!
