### ISSUE TITLE
ExifInterface only supports saving attributes on JPEG formats - Android only

### ISSUE THREAD

**Issue by sergiulucaci** [ggunti/react-native-amazing-cropper#33]
Whenever I try to crop an image from Android Gallery's emulator - (I am using Genymotion; though, on real device it seems to work) I get this:

> ExifInterface only supports saving attributes on JPEG formats.

Any idea?

**Comment by ggunti** [comment]
I will check it. It is a warning or an error message?

**Comment by sergiulucaci** [comment]
No red screen, just a console warning, but **onDone** handler is never called.

*Edited*
<img width="1440" alt="Screenshot 2020-05-15 14 48 59" src="https://user-images.githubusercontent.com/16645155/82047369-5c4fb600-96bb-11ea-8afe-8b50330d85aa.png">

This is how it looks like. 
Flow: 
1. open gallery and choose image from Genymotion's emulator
2. put the image uri into AmazingCropper 
3. crop the image and press "Done"
4. nothing happens

**Comment by ggunti** [comment]
It does not happen to me.

I added an image to emulator gallery:
<img width="344" alt="Captură de ecran din 2020-05-15 la 20 23 04" src="https://user-images.githubusercontent.com/26307699/82079000-c92e7480-96ea-11ea-8dcb-f7e427b20290.png">

Then, I used it as the cropper uri:
```javascript
      <AmazingCropper
        onDone={this.onDone}
        onCancel={this.onCancel}
        imageUri='file:///storage/emulated/0/Download/shoot.png'
        imageWidth={436}
        imageHeight={714}
        NOT_SELECTED_AREA_OPACITY={0.3}
        BORDER_WIDTH={20}
      />
```
<img width="344" alt="Captură de ecran din 2020-05-15 la 20 31 39" src="https://user-images.githubusercontent.com/26307699/82079188-1dd1ef80-96eb-11ea-90fe-a259e1300d23.png">

After that, I pressed the `Done` button and `onDone` was invoked as it should:
<img width="1680" alt="Captură de ecran din 2020-05-15 la 20 34 42" src="https://user-images.githubusercontent.com/26307699/82079472-92a52980-96eb-11ea-832f-db67984712ae.png">

I added `onError` handler, you could use it to find what's the problem in your case.
