### ISSUE TITLE
Size and rotation

### ISSUE THREAD

**Issue by kalideir** [ggunti/react-native-amazing-cropper#37]
Hi

Thank you @ggunti for this component, it's been very useful for my current project.

I am trying to make the crop component full screen, using position absolute and other techniques like flex: 1, is not helping achieve the goal. Is there a way to make this possible?

I also noticed the cropping area moves when touched with two fingers at once, how can I make it still?

**Comment by ggunti** [comment]
Hi @Decoder3-14 
I'm not sure if I understood exactly what you want to achieve, but maybe try to set `BORDER_WIDTH={0}`.

Regarding "I also noticed the cropping area moves when touched with two fingers at once, how can I make it still?":

Please check this [pull request](https://github.com/ggunti/react-native-amazing-cropper/pull/26). As I mentioned in that conversation, I was unable to reproduce the problem. If you can help me to reproduce the problem, I will merge that fix.
