### ISSUE TITLE
Selected image and cropping image both are different 

### ISSUE THREAD

**Issue by Ektasahusahu** [ggunti/react-native-amazing-cropper#4]
I am selecting a different part of image but the cropping image are different.

I am passing camera capture image uri path.

Here is the code:
  <AmazingCropper
            onDone={this.onDone}
            onCancel={this.onCancel}
            imageUri={this.state.image.uri}
            imageWidth={1600}
            imageHeight={2396}
             NOT_SELECTED_AREA_OPACITY={0.3}
             BORDER_WIDTH={20}
          />

please help me thank you.

**Comment by ggunti** [comment]
Where is the code?
