### ISSUE TITLE
Warning msg about bridge.imageLoader is deprecated observed.

### ISSUE THREAD

**Issue by MystL** [ggunti/react-native-amazing-cropper#43]
Hi,

I'm getting the following Warning in log and wondering if there are any fixes for this?

```
WARN     Calling bridge.imageLoader is deprecated and will not work in newer versions of RN. Please update to the moduleForClass API or turboModuleLookupDelegate API.
```

<img width="360" alt="スクリーンショット 2021-02-05 午後3 42 36" src="https://user-images.githubusercontent.com/2239656/107004110-c7509800-67c8-11eb-8012-b68a14537f66.png">

Here's my current dependencies setup
```
"@react-native-community/image-editor": "^2.3.0",
"react": "16.11.0",
"react-native-amazing-cropper": "^0.1.4",
"react-native-image-rotate": "^2.1.0",
```

TIA.

**Comment by ggunti** [comment]
This warning happens because of the `react-native-image-rotate` library (we use it as dependency).
I made a pull request for solving this warning: https://github.com/dgladkov/react-native-image-rotate/pull/19

Please wait to be merged.

**Comment by AdamSheaHewett** [comment]
I would be very grateful if you could merge the fix to this. It's a persistent problem.
