### ISSUE TITLE
Android cropping

### ISSUE THREAD

**Issue by joshwinter** [ggunti/react-native-amazing-cropper#5]
Hello,

For Android - after the crop is complete, it doesn't seem to be passing the actual cropped portion to the variable like it does in iOS, it's just returning the full image. Any clues as to what the problem may be?

onDone = croppedImageUri => {

Thanks!

**Comment by Ektasahusahu** [comment]
I am also facing same issue in android...

**Comment by Ektasahusahu** [comment]
@joshwinter i just check that we have to pass the given image height and width also than we will get the exact cropped image see...

<AmazingCropper
            onDone={this.onDone}
            onCancel={this.onCancel}
            imageUri={this.state.image.uri}
            imageWidth={this.state.image.width}
            imageHeight={this.state.image.height}
             NOT_SELECTED_AREA_OPACITY={0.3}
             BORDER_WIDTH={20}
          />

try this...

**Comment by joshwinter** [comment]
Okay thanks! I will try now.

**Comment by joshwinter** [comment]
@Ektasahusahu 
Unfortunately, I just checked and I'm passing the width and height in the example, but it's still not returning the cropped image in the croppedImageUri  variable. We're you able to get it working?
If yes, does your code look like this?
```
<AmazingCropper
        onDone={this.onDone}
        onCancel={this.onCancel}
        imageUri='https://www.lifeofpix.com/wp-content/uploads/2018/09/manhattan_-11-1600x2396.jpg'
        imageWidth={1600}
        imageHeight={2396}
        NOT_SELECTED_AREA_OPACITY={0.3}
        BORDER_WIDTH={20}
      />
```

**Comment by joshwinter** [comment]
@ggunti Just wanted to see if you have problems on your end for Android or if I'm doing something wrong.

**Comment by ggunti** [comment]
I just tested it and seems that it works also on android without any problems. Try to reproduce what I did.

My code:
<img width="1381" alt="Captură de ecran din 2019-04-10 la 19 04 27" src="https://user-images.githubusercontent.com/26307699/55894804-88992900-5bc3-11e9-8a7b-807b7d802058.png">


When we run it:
<img width="346" alt="Captură de ecran din 2019-04-10 la 18 53 10" src="https://user-images.githubusercontent.com/26307699/55894348-a1eda580-5bc2-11e9-8492-234729be9974.png">

Press DONE and obtain:
<img width="346" alt="Captură de ecran din 2019-04-10 la 18 53 29" src="https://user-images.githubusercontent.com/26307699/55894384-aade7700-5bc2-11e9-9981-824399ef2461.png">

As you can see, the resulted image is the cropped one.
I also tested it on real device and it worked.

**Comment by joshwinter** [comment]
Wonderful. Thank you very much for the code sample. There's something I'm doing wrong then. I'm going to try this today.
