### ISSUE TITLE
unable to crop image taken from camera Android

### ISSUE THREAD

**Issue by amaddurrani** [ggunti/react-native-amazing-cropper#58]
Hi,
I am unable to crop image directly taken from android camera but if i take image from gallery it works perfectly fine i am stuck in it 

<AmazingCropper
       
        onDone={this.onDone}
        onError={this.onError}
        onCancel={this.onCancel}
        imageUri={uri}
        imageWidth={width} //getting width of image
        imageHeight={height} //getting height of image
        NOT_SELECTED_AREA_OPACITY={0.3}
        BORDER_WIDTH={30}
      />
      
      if i crop image from mid in result it shows the part of image left upper side from the crop area

**Comment by ggunti** [comment]
Please try the new version 0.2.3, it should solve your problem.
