### ISSUE TITLE
please add an example project , doesnt work on "react-native": "0.59.5",

### ISSUE THREAD

**Issue by zahidahmed024** [ggunti/react-native-amazing-cropper#7]

**Comment by ggunti** [comment]
What's the problem on "react-native": "0.59.5" ? ImageStore is deprecated but still can be used. It will be changed soon.

**Comment by ggunti** [comment]
Anyhow, you are free to use `readFile(filepath, 'base64')` method from `react-native-fs`. ImageStore is used only in examples to obtain the base64Image, the cropper itself do not depend on ImageStore.

The library works still on "react-native": "0.59.9", I tested it both on android and iOS
